### ISSUE TITLE
Need help for error : No Secure Channel 

### ISSUE THREAD

**Issue by finalburner** [node-opcua/node-opcua#341]
Hi everyone,

I want to let the session of my client nodeopc-ua connected for an undetermined amount of time. how can I keep my session open ? For now, after a period of time receive the following error from the server :
` No SecureChannel , connection may have been canceled abruptly by server `

Hence, my second question : How to establish a secured connection to the server ?

Thanks in advance for your responses

@erossignon

**Comment by erossignon** [comment]
In order to prevent the connection to timeout and server to automatically disconnect, you can either:

- Periodically send a request to the server
- or, set the ```keepSessionAlive```flag to true in the constructor option of your client
```
    var options = {
            keepSessionAlive: true,
    };
       client = new opcua.OPCUAClient(options);
````
- or, make sure you have at least a running subscription ( with or without monitored items)
