### ISSUE TITLE
How to define a complex type with node-opcua?

### ISSUE THREAD

**Issue by enobufs** [node-opcua/node-opcua#346]
This is a question.
I would like to define a complex variable on the server, but I am not sure how I can achieve it with node-opcua. Do you have any example code for me to look into?

A simple example would be:
```
ObjectNode
  + "DeviceInfo" - VariableNode(DataVariable) with a complex type
       + "DeviceName" - VariableNode(DataVariable) of type String
       + "DeviceVersion" - VariableNode(DataVariable) of type Int32
```

**Comment by msalafia** [comment]
@enobufs as i know you should be use an ExtensionObject in order to encode a custom structured value. As i can see from #320 ExtensionObject type is not supported yet. I think this is a serious lack of  node-opcua stack.

@erossignon any updates about the possibility to create custom Structured DataType?
