### ISSUE TITLE
Question: diagnosticInfos in API - YES or NO?

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua#436]
Hi,

just a question.

ClientSession.prototype.readAllAttributes did not use/submit the diagnosticInfos of the read function with the callback.
Why? Are the diagnosticInfos to ignore for the future?

Thank you!
Klaus

**Comment by erossignon** [comment]
Yes, we need to revisit the way diagnostics info will be returned to the client.
At this time, there is work ongoing due to the current addition of Promise support; version 0.2.2 will normalise async client call, and change the way we can access diagnostic info.
In order to have a straight and easy use of async/await syntax , Promisify functions must only return one single return value.

If you are relying on diagnosticsInfo, this will impact your code.
 You can still use raw call to standard OPCUA service if you wish to have full control of every single parameter not offered by higher level apI.
