### ISSUE TITLE
Is there a way we can get browsename for the given nodeid in node opcua ?

### ISSUE THREAD

**Issue by samminen** [node-opcua/node-opcua#588]
In my node opcua client, under monitoredItem() function, I want to print browsename for corresponding node ID. Because printing node ID and its value is not a user friendly to read.

Please suggest the fix ?

monitoredItem.on("changed",function(dataValue){
               if(dataValue.value != null) {
                    console.log(monitoredItem.itemToMonitor.nodeId.toString()," Value changed:  " + dataValue.value.value);
               }
           });

**Comment by anthrogan** [comment]
Depends how you are setting up your monitored items if I'm understanding correctly?

For example I collect a big `tags` array in a file, that contain OPC tag address and a meaning plus facility, like so:
```js
  { 
    Facility: "Bushpress", 
    Tags: {
      Running: "ns=1;s=t|BushPress_DB120_Running",
      Fault: "ns=1;s=t|BushPress_DB120_Fault",
      InfeedEmpty: "ns=1;s=t|BushPress_DB120_InFeedEmpty",
      OutfeedBlock: "ns=1;s=t|BushPress_DB120_OutFeedBlock",
    }
  }
```

We set up a monitored item for each address and a callback as part of the monitoredItem. It's a bit call back hellish because of how our tag objects are built. Also this only happens when a session is either started or restarted so it's not a constant overhead.
```js
// Import all the tags from the file
  let items = require("../../config/opcTags/tags");
  // for each tag in the tags prop, setup a subscription
  items.forEach((facility) => {
    // loop through each prop in the Object
    for (const prop in facility) {
      // pick out the tags
      if (prop === 'Tags') {
        const tags = facility['Tags'];
        for (const address in tags) {
          if (tags.hasOwnProperty(address)) {
            // assign element as the address string
            const element = tags[address];
            // monitor each item
            let monitoredItem = theSubscription.monitor({
              nodeId: opcua.resolveNodeId(element),
              attributeId: opcua.AttributeIds.Value
            }, {
                samplingInterval: 1000,
                discardOldest: true,
                queueSize: 10          
            });
            // monitored item with call back
            monitoredItem.on("changed", function(dataValue) {
                // each change calls the callback function with values collected
                // from the forEach on monitor setup, 
               // effectively building a callback per address monitored
                emitData(facility.Facility, address, dataValue)
              }
            );
          }
        }
      }
    }
  });
};
```
then in your emitData function you can have simply 
```js
  function emitData(facility, tag, dataValue) {
    console.log(facility, tag, dataValue.value.value)
  }
```
And you would get out a console log of `Bushpress OutfeedBlock true` for example.

We have it setup this way because we need to assign values back to different machines, as mentioned it's no use just getting back a value without knowing what its came from, in our case we don't even what the tag address, we need additional information. Hope this helps/makes sense. Also we got to this solution by using the examples as a guide, they are definitely worth a read.
