### ISSUE TITLE
Returning bad quality from sample server

### ISSUE THREAD

**Issue by plcpeople** [node-opcua/node-opcua#8]
Hi,

I tried modifying the sample server to talk to a real PLC as a test.  It worked well, but I wasn't sure how to return a bad status code to the client.  Possibly:

return new opcua.Variant({dataType: opcua.DataType.Double, value: pump_speed, statusCode: opcua.StatusCodes.BadCommunicationError });

But that obviously isn't the right way.  What is the best way to do this?  Or will the status code always be "Good"?

Thanks...
Dana

**Comment by erossignon** [comment]
@plcpeople I hope everything is OK in regard to this issue. I'll close it for now. Feel free to reopen if necessary.

**Comment by On3byT** [comment]
Hi Erossignon,

Actually I have the same problem. I want return a specific StatusCode when a client is reading a variable.
I already checked your posts above and I saw that you fixed it in 2014. But I cant return a StatusCode instead of a Variant in the Getter of a variable in the version 2.33

So what can I do?

Thank you for your effort.

Best regards On3
