### ISSUE TITLE
 Error("Parent folder must be of FolderType " + folder.typeDefinition.toString());

### ISSUE THREAD

**Issue by AndreasHeine** [node-opcua/node-opcua#902]
Hey Etienne,

I try to organize my addressspace a little and i am getting a confusing error i want to create a folder as children of an BaseObjectType-Node similar to:

![Unbenannt](https://user-images.githubusercontent.com/56362817/97765012-dca29000-1b10-11eb-9760-607cf3b06505.PNG)

but i get:
> throw new Error("Parent folder must be of FolderType " + folder.typeDefinition.toString());
> Error: Parent folder must be of FolderType ns=0;i=58

```js

        const addressSpace = server.engine.addressSpace;
        const namespace = addressSpace.registerNamespace("http://testnamespace/ua/");

        const myNode = namespace.addObject({
            organizedBy: addressSpace.rootFolder.objects,
            browseName: "myNode"
        });

        const myfolder = namespace.addFolder(
            myNode,
            {
            browseName: "myFolder"
            }
        );
```

lg Andreas

**Comment by erossignon** [comment]
Hi Andreas,

You would need to  use a different way: 

````javascript

    const namespace = addressSpace.getOwnNamespace();

    const myFolder = namespace.addObject({
        browseName: "MyNewFolder",
        organizedBy: addressSpace.rootFolder.objects.server,
        typeDefinition: "FolderType",
    });

````

**Comment by erossignon** [comment]
The reason why addFolder restricts parent object to be of type FolderType is due to this statement in the OPCUA Specification:
![image](https://user-images.githubusercontent.com/680220/97785096-423f5c80-1ba3-11eb-8f04-526aecba2c93.png)

The SourceNode of such a Reference should always be a View or an Object of the ObjectType FolderType; the TargetNode can be of any NodeClass.

So strickly speaking "MyNode" must be of type "FolderType"

````
   const myNode = namespace.addObject({
            organizedBy: addressSpace.rootFolder.objects,
            browseName: "myNode"
             typeDefinition: "FolderType",
        });
````

**Comment by AndreasHeine** [comment]
Thanks! ;)
